const series = [
    { id: 'smash', name: 'Super Smash Bros. Series', color: '#206BAD' },
    { id: 'mario', name: 'Super Mario Series', color: '#C64143' },
    { id: 'mario_30', name: 'Super Mario 30th Anniversary Series', color: '#C64143' },
    { id: 'my_mario', name: 'My Mario Series', color: '#B28C00' },
    { id: 'skylanders', name: 'Skylanders Series', color: '#D9713A' },
    { id: 'donkey_kong', name: 'Donkey Kong Series', color: '#7F5000' },
    { id: 'yoshi', name: 'Yoshi\'s Woolly World Series', color: '#49AB30' },
    { id: 'power_up', name: 'Power-Up Band Series', color: '#D8C747' },
    { id: 'zelda', name: 'The Legend of Zelda Series', color: '#A59260' },
    { id: 'splatoon', name: 'Splatoon Series', color: '#DBA02B' },
    { id: 'animal_crossing', name: 'Animal Crossing Series', color: '#B0C12E' },
    { id: 'kirby', name: 'Kirby Series', color: '#F698B0' },
    { id: 'kirby_air_riders', name: 'Kirby Air Riders Series', color: '#9BB1CC' },
    { id: 'metroid', name: 'Metroid Series', color: '#742635' },
    { id: 'fire_emblem', name: 'Fire Emblem Series', color: '#BA5F6E' },
    { id: 'monster_hunter', name: 'Monster Hunter Series', color: '#63ACD3' },
    { id: 'shovel_knight', name: 'Shovel Knight Series', color: '#5E3E7D' },
    { id: 'xenoblade', name: 'Xenoblade Chronicles Series', color: '#21A5A7' },
    { id: 'pikmin', name: 'Pikmin Series', color: '#7EAF13' },
    { id: 'boxboy', name: 'Goodbye! BoxBoy! Series', color: '#777777' },
    { id: 'chibi_robo', name: 'Chibi-Robo Series', color: '#8B8A8E' },
    { id: 'detective_pikachu', name: 'Detective Pikachu Series', color: '#965310' },
    { id: 'dark_souls', name: 'Dark Souls Series', color: '#585858' },
    { id: 'diablo', name: 'Diablo Series', color: '#B8381B' },
    { id: 'mega_man', name: 'Mega Man Series', color: '#81A893' },
    { id: 'street_fighter', name: 'Street Fighter Series', color: '#09BEC4' },
    { id: 'resident_evil', name: 'Resident Evil Series', color: '#52372C' },
    { id: 'pragmata', name: 'Pragmata Series', color: '#003AA5' }
];

const amiibo = [
    // Super Smash Bros. Series
    { id: 'smash_01', name: 'Mario', series: 'smash' },
    { id: 'smash_02', name: 'Peach', series: 'smash' },
    { id: 'smash_03', name: 'Yoshi', series: 'smash' },
    { id: 'smash_04', name: 'Donkey Kong', series: 'smash' },
    { id: 'smash_05', name: 'Link', series: 'smash' },
    { id: 'smash_06', name: 'Fox', series: 'smash' },
    { id: 'smash_07', name: 'Samus', series: 'smash' },
    { id: 'smash_08', name: 'Wii Fit Trainer', series: 'smash' },
    { id: 'smash_09', name: 'Villager', series: 'smash' },
    { id: 'smash_10', name: 'Pikachu', series: 'smash' },
    { id: 'smash_11', name: 'Kirby', series: 'smash' },
    { id: 'smash_12', name: 'Marth', series: 'smash' },
    { id: 'smash_13', name: 'Zelda', series: 'smash' },
    { id: 'smash_14', name: 'Diddy Kong', series: 'smash' },
    { id: 'smash_15', name: 'Luigi', series: 'smash' },
    { id: 'smash_16', name: 'Little Mac', series: 'smash' },
    { id: 'smash_17', name: 'Pit', series: 'smash' },
    { id: 'smash_18', name: 'Captain Falcon', series: 'smash' },
    { id: 'smash_19', name: 'Rosalina', series: 'smash' },
    { id: 'smash_20', name: 'Bowser', series: 'smash' },
    { id: 'smash_21', name: 'Lucario', series: 'smash' },
    { id: 'smash_22', name: 'Toon Link', series: 'smash' },
    { id: 'smash_23', name: 'Sheik', series: 'smash' },
    { id: 'smash_24', name: 'Ike', series: 'smash' },
    { id: 'smash_25', name: 'Shulk', series: 'smash' },
    { id: 'smash_26', name: 'Sonic', series: 'smash' },
    { id: 'smash_27', name: 'Mega Man', series: 'smash' },
    { id: 'smash_28', name: 'King Dedede', series: 'smash' },
    { id: 'smash_29', name: 'Meta Knight', series: 'smash' },
    { id: 'smash_30', name: 'Robin', series: 'smash' },
    { id: 'smash_31', name: 'Lucina', series: 'smash' },
    { id: 'smash_32', name: 'Wario', series: 'smash' },
    { id: 'smash_33', name: 'Charizard', series: 'smash' },
    { id: 'smash_34', name: 'Ness', series: 'smash' },
    { id: 'smash_35', name: 'PAC-MAN', series: 'smash' },
    { id: 'smash_36', name: 'Greninja', series: 'smash' },
    { id: 'smash_37', name: 'Jigglypuff', series: 'smash' },
    { id: 'smash_38', name: 'Palutena', series: 'smash' },
    { id: 'smash_39', name: 'Dark Pit', series: 'smash' },
    { id: 'smash_40', name: 'Zero Suit Samus', series: 'smash' },
    { id: 'smash_41', name: 'Ganondorf', series: 'smash' },
    { id: 'smash_42', name: 'Dr. Mario', series: 'smash' },
    { id: 'smash_43', name: 'Bowser Jr.', series: 'smash' },
    { id: 'smash_44', name: 'Olimar', series: 'smash' },
    { id: 'smash_45', name: 'Mr. Game & Watch', series: 'smash' },
    { id: 'smash_46', name: 'R.O.B. (NES)', series: 'smash' },
    { id: 'smash_47', name: 'Duck Hunt Duo', series: 'smash' },
    { id: 'smash_48', name: 'Mii Brawler', series: 'smash' },
    { id: 'smash_49', name: 'Mii Swordfighter', series: 'smash' },
    { id: 'smash_50', name: 'Mii Gunner', series: 'smash' },
    { id: 'smash_51', name: 'Mewtwo', series: 'smash' },
    { id: 'smash_52', name: 'Falco', series: 'smash' },
    { id: 'smash_53', name: 'Lucas', series: 'smash' },
    { id: 'smash_54', name: 'R.O.B. (Famicom)', series: 'smash' },
    { id: 'smash_55', name: 'Roy', series: 'smash' },
    { id: 'smash_56', name: 'Ryu', series: 'smash' },
    { id: 'smash_57', name: 'Cloud', series: 'smash' },
    { id: 'smash_58', name: 'Cloud – Player 2', series: 'smash' },
    { id: 'smash_59', name: 'Corrin', series: 'smash' },
    { id: 'smash_60', name: 'Corrin – Player 2', series: 'smash' },
    { id: 'smash_61', name: 'Bayonetta', series: 'smash' },
    { id: 'smash_62', name: 'Bayonetta – Player 2', series: 'smash' },
    { id: 'smash_63', name: 'Wolf', series: 'smash' },
    { id: 'smash_64', name: 'Inkling', series: 'smash' },
    { id: 'smash_65', name: 'Ridley', series: 'smash' },
    { id: 'smash_66', name: 'Piranha Plant', series: 'smash' },
    { id: 'smash_67', name: 'King K. Rool', series: 'smash' },
    { id: 'smash_68', name: 'Ice Climbers', series: 'smash' },
    { id: 'smash_69', name: 'Ken', series: 'smash' },
    { id: 'smash_70', name: 'Young Link', series: 'smash' },
    { id: 'smash_71', name: 'Daisy', series: 'smash' },
    { id: 'smash_72', name: 'Pichu', series: 'smash' },
    { id: 'smash_73', name: 'Isabelle', series: 'smash' },
    { id: 'smash_74', name: 'Pokémon Trainer', series: 'smash' },
    { id: 'smash_75', name: 'Snake', series: 'smash' },
    { id: 'smash_76', name: 'Ivysaur', series: 'smash' },
    { id: 'smash_77', name: 'Squirtle', series: 'smash' },
    { id: 'smash_78', name: 'Simon', series: 'smash' },
    { id: 'smash_79', name: 'Incineroar', series: 'smash' },
    { id: 'smash_80', name: 'Chrom', series: 'smash' },
    { id: 'smash_81', name: 'Dark Samus', series: 'smash' },
    { id: 'smash_82', name: 'Richter', series: 'smash' },
    { id: 'smash_83', name: 'Joker', series: 'smash' },
    { id: 'smash_84', name: 'Hero', series: 'smash' },
    { id: 'smash_85', name: 'Banjo & Kazooie', series: 'smash' },
    { id: 'smash_86', name: 'Terry', series: 'smash' },
    { id: 'smash_87', name: 'Byleth', series: 'smash' },
    { id: 'smash_88', name: 'Min Min', series: 'smash' },
    { id: 'smash_89', name: 'Steve', series: 'smash' },
    { id: 'smash_90', name: 'Alex', series: 'smash' },
    { id: 'smash_91', name: 'Sephiroth', series: 'smash' },
    { id: 'smash_92', name: 'Kazuya', series: 'smash' },
    { id: 'smash_93', name: 'Pyra', series: 'smash' },
    { id: 'smash_94', name: 'Mythra', series: 'smash' },
    { id: 'smash_95', name: 'Sora', series: 'smash' },

    // Super Mario Series
    { id: 'mario_01', name: 'Mario', series: 'mario' },
    { id: 'mario_02', name: 'Luigi', series: 'mario' },
    { id: 'mario_03', name: 'Peach', series: 'mario' },
    { id: 'mario_04', name: 'Toad', series: 'mario' },
    { id: 'mario_05', name: 'Bowser', series: 'mario' },
    { id: 'mario_06', name: 'Yoshi', series: 'mario' },
    { id: 'mario_07', name: 'Mario - Gold Edition', series: 'mario' },
    { id: 'mario_08', name: 'Mario - Silver Edition', series: 'mario' },
    { id: 'mario_09', name: 'Boo', series: 'mario' },
    { id: 'mario_10', name: 'Donkey Kong', series: 'mario' },
    { id: 'mario_11', name: 'Wario', series: 'mario' },
    { id: 'mario_12', name: 'Rosalina', series: 'mario' },
    { id: 'mario_13', name: 'Waluigi', series: 'mario' },
    { id: 'mario_14', name: 'Daisy', series: 'mario' },
    { id: 'mario_15', name: 'Diddy Kong', series: 'mario' },
    { id: 'mario_16', name: 'Goomba', series: 'mario' },
    { id: 'mario_17', name: 'Koopa Troopa', series: 'mario' },
    { id: 'mario_18', name: 'Mario – Wedding Outfit', series: 'mario' },
    { id: 'mario_19', name: 'Peach – Wedding Outfit', series: 'mario' },
    { id: 'mario_20', name: 'Bowser – Wedding Outfit', series: 'mario' },
    { id: 'mario_21', name: 'Super Mario Cereal', series: 'mario' },
    { id: 'mario_22', name: 'Cat Mario', series: 'mario' },
    { id: 'mario_23', name: 'Cat Peach', series: 'mario' },
    { id: 'mario_24', name: 'Mario and Luma', series: 'mario' },
    { id: 'mario_25', name: 'Rosalina and Lumas', series: 'mario' },
    { id: 'mario_26', name: 'Elephant Mario', series: 'mario' },
    { id: 'mario_27', name: 'Poplin & Prince Florian', series: 'mario' },
    { id: 'mario_28', name: 'Captain Toad & Talking Flower', series: 'mario' },

    // Super Mario 30th Anniversary Series
    { id: 'mario_30_01', name: '30th Anniversary Mario - Classic Colours', series: 'mario_30' },
    { id: 'mario_30_02', name: '30th Anniversary Mario - Modern Colours', series: 'mario_30' },

    // My Mario Series
    { id: 'my_mario_01', name: 'Mario', series: 'my_mario' },
    { id: 'my_mario_02', name: 'Luigi', series: 'my_mario' },
    { id: 'my_mario_03', name: 'Peach', series: 'my_mario' },
    { id: 'my_mario_04', name: 'Yoshi', series: 'my_mario' },

    // Skylanders Series
    { id: 'skylanders_01', name: 'Turbo Charge Donkey Kong', series: 'skylanders' },
    { id: 'skylanders_02', name: 'Barrel Blaster', series: 'skylanders' },
    { id: 'skylanders_03', name: 'Dark Turbo Charge Donkey Kong', series: 'skylanders' },
    { id: 'skylanders_04', name: 'Dark Barrel Blaster', series: 'skylanders' },
    { id: 'skylanders_05', name: 'Hammer Slam Bowser', series: 'skylanders' },
    { id: 'skylanders_06', name: 'Clown Cruiser', series: 'skylanders' },
    { id: 'skylanders_07', name: 'Dark Hammer Slam Bowser', series: 'skylanders' },
    { id: 'skylanders_08', name: 'Dark Clown Cruiser', series: 'skylanders' },

    // Donkey Kong Series
    { id: 'donkey_kong_01', name: 'Donkey Kong & Pauline', series: 'donkey_kong' },

    // Yoshi's Woolly World Series
    { id: 'yoshi_01', name: 'Green Yarn Yoshi', series: 'yoshi' },
    { id: 'yoshi_02', name: 'Pink Yarn Yoshi', series: 'yoshi' },
    { id: 'yoshi_03', name: 'Light Blue Yarn Yoshi', series: 'yoshi' },
    { id: 'yoshi_04', name: 'Mega Yarn Yoshi', series: 'yoshi' },
    { id: 'yoshi_05', name: 'Yarn Poochy', series: 'yoshi' },

    // Power-Up Band Series
    { id: 'power_up_01', name: 'Mario Power-Up Band', series: 'power_up' },
    { id: 'power_up_02', name: 'Luigi Power-Up Band', series: 'power_up' },
    { id: 'power_up_03', name: 'Peach Power-Up Band', series: 'power_up' },
    { id: 'power_up_04', name: 'Daisy Power-Up Band', series: 'power_up' },
    { id: 'power_up_05', name: 'Toad Power-Up Band', series: 'power_up' },
    { id: 'power_up_06', name: 'Yoshi Power-Up Band', series: 'power_up' },
    { id: 'power_up_07', name: 'Mario Power-Up Band – Gold Edition', series: 'power_up' },
    { id: 'power_up_08', name: 'Donkey Kong Power-Up Band', series: 'power_up' },
    { id: 'power_up_09', name: 'Diddy Kong Power-Up Band', series: 'power_up' },

    // The Legend of Zelda Series
    { id: 'zelda_01', name: 'Wolf Link', series: 'zelda' },
    { id: 'zelda_02', name: '30th Anniversary Link', series: 'zelda' },
    { id: 'zelda_03', name: 'Link – Ocarina of Time', series: 'zelda' },
    { id: 'zelda_04', name: 'Toon Link – The Wind Waker', series: 'zelda' },
    { id: 'zelda_05', name: 'Zelda – The Wind Waker', series: 'zelda' },
    { id: 'zelda_06', name: 'Link (Archer)', series: 'zelda' },
    { id: 'zelda_07', name: 'Link (Rider)', series: 'zelda' },
    { id: 'zelda_08', name: 'Guardian', series: 'zelda' },
    { id: 'zelda_09', name: 'Zelda', series: 'zelda' },
    { id: 'zelda_10', name: 'Bokoblin', series: 'zelda' },
    { id: 'zelda_11', name: "Link – Majora's Mask", series: 'zelda' },
    { id: 'zelda_12', name: 'Link – Skyward Sword', series: 'zelda' },
    { id: 'zelda_13', name: 'Link – Twilight Princess', series: 'zelda' },
    { id: 'zelda_14', name: 'Daruk', series: 'zelda' },
    { id: 'zelda_15', name: 'Mipha', series: 'zelda' },
    { id: 'zelda_16', name: 'Revali', series: 'zelda' },
    { id: 'zelda_17', name: 'Urbosa', series: 'zelda' },
    { id: 'zelda_18', name: "Link – Link's Awakening", series: 'zelda' },
    { id: 'zelda_19', name: 'Zelda & Loftwing', series: 'zelda' },
    { id: 'zelda_20', name: 'Link – Tears of the Kingdom', series: 'zelda' },
    { id: 'zelda_21', name: 'Zelda – Tears of the Kingdom', series: 'zelda' },
    { id: 'zelda_22', name: 'Ganondorf – Tears of the Kingdom', series: 'zelda' },
    { id: 'zelda_23', name: 'Tulin', series: 'zelda' },
    { id: 'zelda_24', name: 'Yunobo', series: 'zelda' },
    { id: 'zelda_25', name: 'Sidon', series: 'zelda' },
    { id: 'zelda_26', name: 'Riju', series: 'zelda' },

    // Splatoon Series
    { id: 'splatoon_01', name: 'Inkling Boy (Blue)', series: 'splatoon' },
    { id: 'splatoon_02', name: 'Inkling Squid (Lime)', series: 'splatoon' },
    { id: 'splatoon_03', name: 'Inkling Girl (Orange)', series: 'splatoon' },
    { id: 'splatoon_04', name: 'Callie', series: 'splatoon' },
    { id: 'splatoon_05', name: 'Marie', series: 'splatoon' },
    { id: 'splatoon_06', name: 'Inkling Boy (Purple)', series: 'splatoon' },
    { id: 'splatoon_07', name: 'Inkling Squid (Orange)', series: 'splatoon' },
    { id: 'splatoon_08', name: 'Inkling Girl (Lime)', series: 'splatoon' },
    { id: 'splatoon_09', name: 'Inkling Boy', series: 'splatoon' },
    { id: 'splatoon_10', name: 'Inkling Squid', series: 'splatoon' },
    { id: 'splatoon_11', name: 'Inkling Girl', series: 'splatoon' },
    { id: 'splatoon_12', name: 'Pearl', series: 'splatoon' },
    { id: 'splatoon_13', name: 'Marina', series: 'splatoon' },
    { id: 'splatoon_14', name: 'Octoling Boy', series: 'splatoon' },
    { id: 'splatoon_15', name: 'Octoling Octopus', series: 'splatoon' },
    { id: 'splatoon_16', name: 'Octoling Girl', series: 'splatoon' },
    { id: 'splatoon_17', name: 'Octoling (Blue)', series: 'splatoon' },
    { id: 'splatoon_18', name: 'Inkling (Yellow)', series: 'splatoon' },
    { id: 'splatoon_19', name: 'Smallfry', series: 'splatoon' },
    { id: 'splatoon_20', name: 'Shiver', series: 'splatoon' },
    { id: 'splatoon_21', name: 'Big Man', series: 'splatoon' },
    { id: 'splatoon_22', name: 'Frye', series: 'splatoon' },
    { id: 'splatoon_23', name: 'Callie (Alterna)', series: 'splatoon' },
    { id: 'splatoon_24', name: 'Marie (Alterna)', series: 'splatoon' },
    { id: 'splatoon_25', name: 'Pearl (Side Order)', series: 'splatoon' },
    { id: 'splatoon_26', name: 'Marina (Side Order)', series: 'splatoon' },

    // Animal Crossing Series
    { id: 'animal_crossing_01', name: 'Cyrus', series: 'animal_crossing' },
    { id: 'animal_crossing_02', name: 'Reese', series: 'animal_crossing' },
    { id: 'animal_crossing_03', name: 'Lottie', series: 'animal_crossing' },
    { id: 'animal_crossing_04', name: 'Digby', series: 'animal_crossing' },
    { id: 'animal_crossing_05', name: 'Tom Nook', series: 'animal_crossing' },
    { id: 'animal_crossing_06', name: 'Mabel', series: 'animal_crossing' },
    { id: 'animal_crossing_07', name: 'Isabelle – Winter Outfit', series: 'animal_crossing' },
    { id: 'animal_crossing_08', name: 'K.K.', series: 'animal_crossing' },
    { id: 'animal_crossing_09', name: 'Kicks', series: 'animal_crossing' },
    { id: 'animal_crossing_10', name: 'Resetti', series: 'animal_crossing' },
    { id: 'animal_crossing_11', name: 'Celeste', series: 'animal_crossing' },
    { id: 'animal_crossing_12', name: 'Blathers', series: 'animal_crossing' },
    { id: 'animal_crossing_13', name: 'Rover', series: 'animal_crossing' },
    { id: 'animal_crossing_14', name: 'Timmy & Tommy', series: 'animal_crossing' },
    { id: 'animal_crossing_15', name: "Kapp'n", series: 'animal_crossing' },
    { id: 'animal_crossing_16', name: 'Isabelle – Summer Outfit', series: 'animal_crossing' },

    // Kirby Series
    { id: 'kirby_01', name: 'Kirby', series: 'kirby' },
    { id: 'kirby_02', name: 'Meta Knight', series: 'kirby' },
    { id: 'kirby_03', name: 'King Dedede', series: 'kirby' },
    { id: 'kirby_04', name: 'Waddle Dee', series: 'kirby' },

    // Kirby Air Riders Series
    { id: 'kirby_air_riders_01', name: 'Kirby & Warp Star', series: 'kirby_air_riders' },
    { id: 'kirby_air_riders_02', name: 'Bandana Waddle Dee & Winged Star', series: 'kirby_air_riders' },
    { id: 'kirby_air_riders_03', name: 'Meta Knight & Shadow Star', series: 'kirby_air_riders' },
    { id: 'kirby_air_riders_04', name: 'King Dedede & Tank Star', series: 'kirby_air_riders' },
    { id: 'kirby_air_riders_05', name: 'Chef Kawasaki & Hop Star', series: 'kirby_air_riders' },

    // Metroid Series
    { id: 'metroid_01', name: 'Samus Aran', series: 'metroid' },
    { id: 'metroid_02', name: 'Metroid', series: 'metroid' },
    { id: 'metroid_03', name: 'Samus (Metroid Dread)', series: 'metroid' },
    { id: 'metroid_04', name: 'E.M.M.I', series: 'metroid' },
    { id: 'metroid_05', name: 'Samus (Metroid Prime 4)', series: 'metroid' },
    { id: 'metroid_06', name: 'Samus & Vi-O-La', series: 'metroid' },
    { id: 'metroid_07', name: 'Sylux', series: 'metroid' },

    // Fire Emblem Series
    { id: 'fire_emblem_01', name: 'Alm', series: 'fire_emblem' },
    { id: 'fire_emblem_02', name: 'Celica', series: 'fire_emblem' },
    { id: 'fire_emblem_03', name: 'Chrom', series: 'fire_emblem' },
    { id: 'fire_emblem_04', name: 'Tiki', series: 'fire_emblem' },

    // Monster Hunter Series
    { id: 'monster_hunter_01', name: 'One-Eyed Rathalos & Rider - Male', series: 'monster_hunter' },
    { id: 'monster_hunter_02', name: 'Navirou', series: 'monster_hunter' },
    { id: 'monster_hunter_03', name: 'One-Eyed Rathalos & Rider - Female', series: 'monster_hunter' },
    { id: 'monster_hunter_04', name: 'Barioth & Ayuria', series: 'monster_hunter' },
    { id: 'monster_hunter_05', name: 'Rathian & Cheval', series: 'monster_hunter' },
    { id: 'monster_hunter_06', name: 'Qurupeco & Dan', series: 'monster_hunter' },
    { id: 'monster_hunter_07', name: 'Palamute', series: 'monster_hunter' },
    { id: 'monster_hunter_08', name: 'Magnamalo', series: 'monster_hunter' },
    { id: 'monster_hunter_09', name: 'Palico', series: 'monster_hunter' },
    { id: 'monster_hunter_10', name: 'Ena', series: 'monster_hunter' },
    { id: 'monster_hunter_11', name: 'Razewing Ratha', series: 'monster_hunter' },
    { id: 'monster_hunter_12', name: 'Tsukino', series: 'monster_hunter' },
    { id: 'monster_hunter_13', name: 'Palamute – Canyne Malzeno', series: 'monster_hunter' },
    { id: 'monster_hunter_14', name: 'Malzeno', series: 'monster_hunter' },
    { id: 'monster_hunter_15', name: 'Palico – Felyne Malzeno', series: 'monster_hunter' },
    { id: 'monster_hunter_16', name: 'Ratha', series: 'monster_hunter' },
    { id: 'monster_hunter_17', name: 'Rudy', series: 'monster_hunter' },
    { id: 'monster_hunter_18', name: 'Ratha V', series: 'monster_hunter' },

    // Shovel Knight Series
    { id: 'shovel_knight_01', name: 'Shovel Knight', series: 'shovel_knight' },
    { id: 'shovel_knight_02', name: 'Plague Knight', series: 'shovel_knight' },
    { id: 'shovel_knight_03', name: 'Specter Knight', series: 'shovel_knight' },
    { id: 'shovel_knight_04', name: 'King Knight', series: 'shovel_knight' },
    { id: 'shovel_knight_05', name: 'Shovel Knight – Gold Edition', series: 'shovel_knight' },

    // Xenoblade Chronicles Series
    { id: 'xenoblade_01', name: 'Noah', series: 'xenoblade' },
    { id: 'xenoblade_02', name: 'Mio', series: 'xenoblade' },

    // Pikmin Series
    { id: 'pikmin_01', name: 'Pikmin', series: 'pikmin' },

    // Goodbye! BoxBoy! Series
    { id: 'boxboy_01', name: 'Qbby', series: 'boxboy' },

    // Chibi-Robo Series
    { id: 'chibi_robo_01', name: 'Chibi-Robo', series: 'chibi_robo' },

    // Detective Pikachu Series
    { id: 'detective_pikachu_01', name: 'Detective Pikachu', series: 'detective_pikachu' },

    // Dark Souls Series
    { id: 'dark_souls_01', name: 'Solaire of Astora', series: 'dark_souls' },

    // Diablo Series
    { id: 'diablo_01', name: 'Loot Goblin', series: 'diablo' },

    // Mega Man Series
    { id: 'mega_man_01', name: 'Mega Man – Gold Edition', series: 'mega_man' },
    { id: 'mega_man_02', name: 'Mega Man', series: 'mega_man' },

    // Street Fighter Series
    { id: 'street_fighter_01', name: 'Luke', series: 'street_fighter' },
    { id: 'street_fighter_02', name: 'Jamie', series: 'street_fighter' },
    { id: 'street_fighter_03', name: 'Kimberly', series: 'street_fighter' },

    // Resident Evil Series
    { id: 'resident_evil_01', name: 'Grace', series: 'resident_evil' },
    { id: 'resident_evil_02', name: 'Leon', series: 'resident_evil' },

    // Pragmata Series
    { id: 'pragmata_01', name: 'Diana', series: 'pragmata' }
];