const series = [
    { id: 'ssb', name: 'Super Smash Bros. Series', color: '#206BAD' },
    { id: 'smb', name: 'Super Mario Series', color: '#C64143' },
    { id: 'smb30', name: 'Super Mario 30th Anniversary Series', color: '#C64143' },
    { id: 'smbmy', name: 'My Mario Series', color: '#B28C00' },
    { id: 'sky', name: 'Skylanders Series', color: '#D9713A' },
    { id: 'dk', name: 'Donkey Kong Series', color: '#7F5000' },
    { id: 'yww', name: 'Yoshi\'s Woolly World Series', color: '#49AB30' },
    { id: 'pub', name: 'Power-Up Band Series', color: '#D8C747' },
    { id: 'tloz', name: 'The Legend of Zelda Series', color: '#A59260' },
    { id: 'sp', name: 'Splatoon Series', color: '#DBA02B' },
    { id: 'ac', name: 'Animal Crossing Series', color: '#B0C12E' },
    { id: 'ki', name: 'Kirby Series', color: '#B0C12E' },
    { id: 'me', name: 'Metroid Series', color: '#742635' },
    { id: 'fe', name: 'Fire Emblem Series', color: '#BA5F6E' },
    { id: 'mh', name: 'Monster Hunter Series', color: '#63ACD3' },
    { id: 'sk', name: 'Shovel Knight Series', color: '#5E3E7D' },
    { id: 'xc', name: 'Xenoblade Chronicles Series', color: '#21A5A7' },
    { id: 'pi', name: 'Pikmin Series', color: '#7EAF13' },
    { id: 'bb', name: 'Goodbye! BoxBoy! Series', color: '#777777' },
    { id: 'cr', name: 'Chibi-Robo Series', color: '#8B8A8E' },
    { id: 'dp', name: 'Detective Pikachu Series', color: '#965310' },
    { id: 'ds', name: 'Dark Souls Series', color: '#404040' },
    { id: 'di', name: 'Diablo Series', color: '#B8381B' },
    { id: 'mm', name: 'Mega Man Series', color: '#81A893' },
    { id: 'sf', name: 'Street Fighter Series', color: '#09BEC4' }
];

const amiibos = [
    // Super Smash Bros. Series
    { id: 'ssb_01', name: 'Mario', series: 'ssb' },
    { id: 'ssb_02', name: 'Peach', series: 'ssb' },
    { id: 'ssb_03', name: 'Yoshi', series: 'ssb' },
    { id: 'ssb_04', name: 'Donkey Kong', series: 'ssb' },
    { id: 'ssb_05', name: 'Link', series: 'ssb' },
    { id: 'ssb_06', name: 'Fox', series: 'ssb' },
    { id: 'ssb_07', name: 'Samus', series: 'ssb' },
    { id: 'ssb_08', name: 'Wii Fit Trainer', series: 'ssb' },
    { id: 'ssb_09', name: 'Villager', series: 'ssb' },
    { id: 'ssb_10', name: 'Pikachu', series: 'ssb' },
    { id: 'ssb_11', name: 'Kirby', series: 'ssb' },
    { id: 'ssb_12', name: 'Marth', series: 'ssb' },
    { id: 'ssb_13', name: 'Zelda', series: 'ssb' },
    { id: 'ssb_14', name: 'Diddy Kong', series: 'ssb' },
    { id: 'ssb_15', name: 'Luigi', series: 'ssb' },
    { id: 'ssb_16', name: 'Little Mac', series: 'ssb' },
    { id: 'ssb_17', name: 'Pit', series: 'ssb' },
    { id: 'ssb_18', name: 'Captain Falcon', series: 'ssb' },
    { id: 'ssb_19', name: 'Rosalina', series: 'ssb' },
    { id: 'ssb_20', name: 'Bowser', series: 'ssb' },
    { id: 'ssb_21', name: 'Lucario', series: 'ssb' },
    { id: 'ssb_22', name: 'Toon Link', series: 'ssb' },
    { id: 'ssb_23', name: 'Sheik', series: 'ssb' },
    { id: 'ssb_24', name: 'Ike', series: 'ssb' },
    { id: 'ssb_25', name: 'Shulk', series: 'ssb' },
    { id: 'ssb_26', name: 'Sonic', series: 'ssb' },
    { id: 'ssb_27', name: 'Mega Man', series: 'ssb' },
    { id: 'ssb_28', name: 'King Dedede', series: 'ssb' },
    { id: 'ssb_29', name: 'Meta Knight', series: 'ssb' },
    { id: 'ssb_30', name: 'Robin', series: 'ssb' },
    { id: 'ssb_31', name: 'Lucina', series: 'ssb' },
    { id: 'ssb_32', name: 'Wario', series: 'ssb' },
    { id: 'ssb_33', name: 'Charizard', series: 'ssb' },
    { id: 'ssb_34', name: 'Ness', series: 'ssb' },
    { id: 'ssb_35', name: 'PAC-MAN', series: 'ssb' },
    { id: 'ssb_36', name: 'Greninja', series: 'ssb' },
    { id: 'ssb_37', name: 'Jigglypuff', series: 'ssb' },
    { id: 'ssb_38', name: 'Palutena', series: 'ssb' },
    { id: 'ssb_39', name: 'Dark Pit', series: 'ssb' },
    { id: 'ssb_40', name: 'Zero Suit Samus', series: 'ssb' },
    { id: 'ssb_41', name: 'Ganondorf', series: 'ssb' },
    { id: 'ssb_42', name: 'Dr. Mario', series: 'ssb' },
    { id: 'ssb_43', name: 'Bowser Jr.', series: 'ssb' },
    { id: 'ssb_44', name: 'Olimar', series: 'ssb' },
    { id: 'ssb_45', name: 'Mr. Game & Watch', series: 'ssb' },
    { id: 'ssb_46', name: 'R.O.B. (NES)', series: 'ssb' },
    { id: 'ssb_47', name: 'Duck Hunt Duo', series: 'ssb' },
    { id: 'ssb_48', name: 'Mii Brawler', series: 'ssb' },
    { id: 'ssb_49', name: 'Mii Swordfighter', series: 'ssb' },
    { id: 'ssb_50', name: 'Mii Gunner', series: 'ssb' },
    { id: 'ssb_51', name: 'Mewtwo', series: 'ssb' },
    { id: 'ssb_52', name: 'Falco', series: 'ssb' },
    { id: 'ssb_53', name: 'Lucas', series: 'ssb' },
    { id: 'ssb_54', name: 'R.O.B. (Famicom)', series: 'ssb' },
    { id: 'ssb_55', name: 'Roy', series: 'ssb' },
    { id: 'ssb_56', name: 'Ryu', series: 'ssb' },
    { id: 'ssb_57', name: 'Cloud', series: 'ssb' },
    { id: 'ssb_58', name: 'Cloud – Player 2', series: 'ssb' },
    { id: 'ssb_59', name: 'Corrin', series: 'ssb' },
    { id: 'ssb_60', name: 'Corrin – Player 2', series: 'ssb' },
    { id: 'ssb_61', name: 'Bayonetta', series: 'ssb' },
    { id: 'ssb_62', name: 'Bayonetta – Player 2', series: 'ssb' },
    { id: 'ssb_63', name: 'Wolf', series: 'ssb' },
    { id: 'ssb_64', name: 'Inkling', series: 'ssb' },
    { id: 'ssb_65', name: 'Ridley', series: 'ssb' },
    { id: 'ssb_66', name: 'Piranha Plant', series: 'ssb' },
    { id: 'ssb_67', name: 'King K. Rool', series: 'ssb' },
    { id: 'ssb_68', name: 'Ice Climbers', series: 'ssb' },
    { id: 'ssb_69', name: 'Ken', series: 'ssb' },
    { id: 'ssb_70', name: 'Young Link', series: 'ssb' },
    { id: 'ssb_71', name: 'Daisy', series: 'ssb' },
    { id: 'ssb_72', name: 'Pichu', series: 'ssb' },
    { id: 'ssb_73', name: 'Isabelle', series: 'ssb' },
    { id: 'ssb_74', name: 'Pokémon Trainer', series: 'ssb' },
    { id: 'ssb_75', name: 'Snake', series: 'ssb' },
    { id: 'ssb_76', name: 'Ivysaur', series: 'ssb' },
    { id: 'ssb_77', name: 'Squirtle', series: 'ssb' },
    { id: 'ssb_78', name: 'Simon', series: 'ssb' },
    { id: 'ssb_79', name: 'Incineroar', series: 'ssb' },
    { id: 'ssb_80', name: 'Chrom', series: 'ssb' },
    { id: 'ssb_81', name: 'Dark Samus', series: 'ssb' },
    { id: 'ssb_82', name: 'Richter', series: 'ssb' },
    { id: 'ssb_83', name: 'Joker', series: 'ssb' },
    { id: 'ssb_84', name: 'Hero', series: 'ssb' },
    { id: 'ssb_85', name: 'Banjo & Kazooie', series: 'ssb' },
    { id: 'ssb_86', name: 'Terry', series: 'ssb' },
    { id: 'ssb_87', name: 'Byleth', series: 'ssb' },
    { id: 'ssb_88', name: 'Min Min', series: 'ssb' },
    { id: 'ssb_89', name: 'Steve', series: 'ssb' },
    { id: 'ssb_90', name: 'Alex', series: 'ssb' },
    { id: 'ssb_91', name: 'Sephiroth', series: 'ssb' },
    { id: 'ssb_92', name: 'Kazuya', series: 'ssb' },
    { id: 'ssb_93', name: 'Pyra', series: 'ssb' },
    { id: 'ssb_94', name: 'Mythra', series: 'ssb' },
    { id: 'ssb_95', name: 'Sora', series: 'ssb' },

    // Super Mario Series
    { id: 'smb_01', name: 'Mario', series: 'smb' },
    { id: 'smb_02', name: 'Luigi', series: 'smb' },
    { id: 'smb_03', name: 'Peach', series: 'smb' },
    { id: 'smb_04', name: 'Toad', series: 'smb' },
    { id: 'smb_05', name: 'Bowser', series: 'smb' },
    { id: 'smb_06', name: 'Yoshi', series: 'smb' },
    { id: 'smb_07', name: 'Mario - Gold Edition', series: 'smb' },
    { id: 'smb_08', name: 'Mario - Silver Edition', series: 'smb' },
    { id: 'smb_09', name: 'Boo', series: 'smb' },
    { id: 'smb_10', name: 'Donkey Kong', series: 'smb' },
    { id: 'smb_11', name: 'Wario', series: 'smb' },
    { id: 'smb_12', name: 'Rosalina', series: 'smb' },
    { id: 'smb_13', name: 'Waluigi', series: 'smb' },
    { id: 'smb_14', name: 'Daisy', series: 'smb' },
    { id: 'smb_15', name: 'Diddy Kong', series: 'smb' },
    { id: 'smb_16', name: 'Goomba', series: 'smb' },
    { id: 'smb_17', name: 'Koopa Troopa', series: 'smb' },
    { id: 'smb_18', name: 'Mario – Wedding Outfit', series: 'smb' },
    { id: 'smb_19', name: 'Peach – Wedding Outfit', series: 'smb' },
    { id: 'smb_20', name: 'Bowser – Wedding Outfit', series: 'smb' },
    { id: 'smb_21', name: 'Super Mario Cereal', series: 'smb' },
    { id: 'smb_22', name: 'Cat Mario', series: 'smb' },
    { id: 'smb_23', name: 'Cat Peach', series: 'smb' },
    { id: 'smb_24', name: 'Mario and Luma', series: 'smb' },
    { id: 'smb_25', name: 'Rosalina and Lumas', series: 'smb' },

    // Super Mario 30th Anniversary Series
    { id: 'smb30_01', name: '30th Anniversary Mario - Classic Colours', series: 'smb30' },
    { id: 'smb30_02', name: '30th Anniversary Mario - Modern Colours', series: 'smb30' },

    // My Mario Series
    { id: 'smbmy_01', name: 'Mario', series: 'smbmy' },
    { id: 'smbmy_02', name: 'Luigi', series: 'smbmy' },
    { id: 'smbmy_03', name: 'Peach', series: 'smbmy' },
    { id: 'smbmy_04', name: 'Yoshi', series: 'smbmy' },

    // Skylanders Series
    { id: 'sky_01', name: 'Turbo Charge Donkey Kong', series: 'sky' },
    { id: 'sky_02', name: 'Barrel Blaster', series: 'sky' },
    { id: 'sky_03', name: 'Dark Turbo Charge Donkey Kong', series: 'sky' },
    { id: 'sky_04', name: 'Dark Barrel Blaster', series: 'sky' },
    { id: 'sky_05', name: 'Hammer Slam Bowser', series: 'sky' },
    { id: 'sky_06', name: 'Clown Cruiser', series: 'sky' },
    { id: 'sky_07', name: 'Dark Hammer Slam Bowser', series: 'sky' },
    { id: 'sky_08', name: 'Dark Clown Cruiser', series: 'sky' },

    // Donkey Kong Series
    { id: 'dk_01', name: 'Donkey Kong & Pauline', series: 'dk' },

    // Yoshi's Woolly World Series
    { id: 'yww_01', name: 'Green Yarn Yoshi', series: 'yww' },
    { id: 'yww_02', name: 'Pink Yarn Yoshi', series: 'yww' },
    { id: 'yww_03', name: 'Light Blue Yarn Yoshi', series: 'yww' },
    { id: 'yww_04', name: 'Mega Yarn Yoshi', series: 'yww' },
    { id: 'yww_05', name: 'Yarn Poochy', series: 'yww' },

    // Power-Up Band Series
    { id: 'pub_01', name: 'Mario Power-Up Band', series: 'pub' },
    { id: 'pub_02', name: 'Luigi Power-Up Band', series: 'pub' },
    { id: 'pub_03', name: 'Peach Power-Up Band', series: 'pub' },
    { id: 'pub_04', name: 'Daisy Power-Up Band', series: 'pub' },
    { id: 'pub_05', name: 'Toad Power-Up Band', series: 'pub' },
    { id: 'pub_06', name: 'Yoshi Power-Up Band', series: 'pub' },
    { id: 'pub_07', name: 'Mario Power-Up Band – Gold Edition', series: 'pub' },
    { id: 'pub_08', name: 'Donkey Kong Power-Up Band', series: 'pub' },
    { id: 'pub_09', name: 'Diddy Kong Power-Up Band', series: 'pub' },

    // The Legend of Zelda Series
    { id: 'tloz_01', name: 'Wolf Link', series: 'tloz' },
    { id: 'tloz_02', name: '30th Anniversary Link', series: 'tloz' },
    { id: 'tloz_03', name: 'Link – Ocarina of Time', series: 'tloz' },
    { id: 'tloz_04', name: 'Toon Link – The Wind Waker', series: 'tloz' },
    { id: 'tloz_05', name: 'Zelda – The Wind Waker', series: 'tloz' },
    { id: 'tloz_06', name: 'Link (Archer)', series: 'tloz' },
    { id: 'tloz_07', name: 'Link (Rider)', series: 'tloz' },
    { id: 'tloz_08', name: 'Guardian', series: 'tloz' },
    { id: 'tloz_09', name: 'Zelda', series: 'tloz' },
    { id: 'tloz_10', name: 'Bokoblin', series: 'tloz' },
    { id: 'tloz_11', name: 'Link – Majora\'s Mask', series: 'tloz' },
    { id: 'tloz_12', name: 'Link – Skyward Sword', series: 'tloz' },
    { id: 'tloz_13', name: 'Link – Twilight Princess', series: 'tloz' },
    { id: 'tloz_14', name: 'Daruk', series: 'tloz' },
    { id: 'tloz_15', name: 'Mipha', series: 'tloz' },
    { id: 'tloz_16', name: 'Revali', series: 'tloz' },
    { id: 'tloz_17', name: 'Urbosa', series: 'tloz' },
    { id: 'tloz_18', name: 'Link – Link\'s Awakening', series: 'tloz' },
    { id: 'tloz_19', name: 'Zelda & Loftwing', series: 'tloz' },
    { id: 'tloz_20', name: 'Link – Tears of the Kingdom', series: 'tloz' },
    { id: 'tloz_21', name: 'Zelda – Tears of the Kingdom', series: 'tloz' },
    { id: 'tloz_22', name: 'Ganondorf – Tears of the Kingdom', series: 'tloz' },
    { id: 'tloz_23', name: 'Tulin', series: 'tloz' },
    { id: 'tloz_24', name: 'Yunobo', series: 'tloz' },
    { id: 'tloz_25', name: 'Sidon', series: 'tloz' },
    { id: 'tloz_26', name: 'Riju', series: 'tloz' },

    // Splatoon Series
    { id: 'sp_01', name: 'Inkling Boy (Blue)', series: 'sp' },
    { id: 'sp_02', name: 'Inkling Squid (Lime)', series: 'sp' },
    { id: 'sp_03', name: 'Inkling Girl (Orange)', series: 'sp' },
    { id: 'sp_04', name: 'Callie', series: 'sp' },
    { id: 'sp_05', name: 'Marie', series: 'sp' },
    { id: 'sp_06', name: 'Inkling Boy (Purple)', series: 'sp' },
    { id: 'sp_07', name: 'Inkling Squid (Orange)', series: 'sp' },
    { id: 'sp_08', name: 'Inkling Girl (Lime)', series: 'sp' },
    { id: 'sp_09', name: 'Inkling Boy', series: 'sp' },
    { id: 'sp_10', name: 'Inkling Squid', series: 'sp' },
    { id: 'sp_11', name: 'Inkling Girl', series: 'sp' },
    { id: 'sp_12', name: 'Pearl', series: 'sp' },
    { id: 'sp_13', name: 'Marina', series: 'sp' },
    { id: 'sp_14', name: 'Octoling Boy', series: 'sp' },
    { id: 'sp_15', name: 'Octoling Octopus', series: 'sp' },
    { id: 'sp_16', name: 'Octoling Girl', series: 'sp' },
    { id: 'sp_17', name: 'Octoling (Blue)', series: 'sp' },
    { id: 'sp_18', name: 'Inkling (Yellow)', series: 'sp' },
    { id: 'sp_19', name: 'Smallfry', series: 'sp' },
    { id: 'sp_20', name: 'Shiver', series: 'sp' },
    { id: 'sp_21', name: 'Big Man', series: 'sp' },
    { id: 'sp_22', name: 'Frye', series: 'sp' },
    { id: 'sp_23', name: 'Callie (Alterna)', series: 'sp' },
    { id: 'sp_24', name: 'Marie (Alterna)', series: 'sp' },
    { id: 'sp_25', name: 'Pearl (Side Order)', series: 'sp' },
    { id: 'sp_26', name: 'Marina (Side Order)', series: 'sp' },

    // Animal Crossing Series
    { id: 'ac_01', name: 'Cyrus', series: 'ac' },
    { id: 'ac_02', name: 'Reese', series: 'ac' },
    { id: 'ac_03', name: 'Lottie', series: 'ac' },
    { id: 'ac_04', name: 'Digby', series: 'ac' },
    { id: 'ac_05', name: 'Tom Nook', series: 'ac' },
    { id: 'ac_06', name: 'Mabel', series: 'ac' },
    { id: 'ac_07', name: 'Isabelle – Winter Outfit', series: 'ac' },
    { id: 'ac_08', name: 'K.K.', series: 'ac' },
    { id: 'ac_09', name: 'Kicks', series: 'ac' },
    { id: 'ac_10', name: 'Resetti', series: 'ac' },
    { id: 'ac_11', name: 'Celeste', series: 'ac' },
    { id: 'ac_12', name: 'Blathers', series: 'ac' },
    { id: 'ac_13', name: 'Rover', series: 'ac' },
    { id: 'ac_14', name: 'Timmy & Tommy', series: 'ac' },
    { id: 'ac_15', name: 'Kapp\'n', series: 'ac' },
    { id: 'ac_16', name: 'Isabelle – Summer Outfit', series: 'ac' },

    // Kirby Series
    { id: 'ki_01', name: 'Kirby', series: 'ki' },
    { id: 'ki_02', name: 'Meta Knight', series: 'ki' },
    { id: 'ki_03', name: 'King Dedede', series: 'ki' },
    { id: 'ki_04', name: 'Waddle Dee', series: 'ki' },
    { id: 'ki_05', name: 'Kirby & Warp Star', series: 'ki' },
    { id: 'ki_06', name: 'Bandana Waddle Dee & Winged Star', series: 'ki' },
    { id: 'ki_07', name: 'Meta Knight & Shadow Star', series: 'ki' },
    { id: 'ki_08', name: 'King Dedede & Tank Star', series: 'ki' },
    { id: 'ki_09', name: 'Chef Kawasaki & Hop Star', series: 'ki' },

    // Metroid Series
    { id: 'me_01', name: 'Samus Aran', series: 'me' },
    { id: 'me_02', name: 'Metroid', series: 'me' },
    { id: 'me_03', name: 'Samus', series: 'me' },
    { id: 'me_04', name: 'E.M.M.I', series: 'me' },
    { id: 'me_05', name: 'Samus', series: 'me' },
    { id: 'me_06', name: 'Samus & Vi-O-La', series: 'me' },
    { id: 'me_07', name: 'Sylux', series: 'me' },

    // Fire Emblem Series
    { id: 'fe_01', name: 'Alm', series: 'fe' },
    { id: 'fe_02', name: 'Celica', series: 'fe' },
    { id: 'fe_03', name: 'Chrom', series: 'fe' },
    { id: 'fe_04', name: 'Tiki', series: 'fe' },

    // Monster Hunter Series
    { id: 'mh_01', name: 'One-Eyed Rathalos & Rider - Male', series: 'mh' },
    { id: 'mh_02', name: 'Navirou', series: 'mh' },
    { id: 'mh_03', name: 'One-Eyed Rathalos & Rider - Female', series: 'mh' },
    { id: 'mh_04', name: 'Barioth & Ayuria', series: 'mh' },
    { id: 'mh_05', name: 'Rathian & Cheval', series: 'mh' },
    { id: 'mh_06', name: 'Qurupeco & Dan', series: 'mh' },
    { id: 'mh_07', name: 'Palamute', series: 'mh' },
    { id: 'mh_08', name: 'Magnamalo', series: 'mh' },
    { id: 'mh_09', name: 'Palico', series: 'mh' },
    { id: 'mh_10', name: 'Ena', series: 'mh' },
    { id: 'mh_11', name: 'Razewing Ratha', series: 'mh' },
    { id: 'mh_12', name: 'Tsukino', series: 'mh' },
    { id: 'mh_13', name: 'Palamute – Canyne Malzeno', series: 'mh' },
    { id: 'mh_14', name: 'Malzeno', series: 'mh' },
    { id: 'mh_15', name: 'Palico – Felyne Malzeno', series: 'mh' },

    // Shovel Knight Series
    { id: 'sk_01', name: 'Shovel Knight', series: 'sk' },
    { id: 'sk_02', name: 'Plague Knight', series: 'sk' },
    { id: 'sk_03', name: 'Specter Knight', series: 'sk' },
    { id: 'sk_04', name: 'King Knight', series: 'sk' },
    { id: 'sk_05', name: 'Shovel Knight – Gold Edition', series: 'sk' },

    // Xenoblade Chronicles Series
    { id: 'xc_01', name: 'Noah', series: 'xc' },
    { id: 'xc_02', name: 'Mio', series: 'xc' },

    // Pikmin Series
    { id: 'pi_01', name: 'Pikmin', series: 'pi' },

    // Goodbye! BoxBoy! Series
    { id: 'bb_01', name: 'Qbby', series: 'bb' },

    // Chibi-Robo Series
    { id: 'cr_01', name: 'Chibi-Robo', series: 'cr' },

    // Detective Pikachu Series
    { id: 'dp_01', name: 'Detective Pikachu', series: 'dp' },

    // Dark Souls Series
    { id: 'ds_01', name: 'Solaire of Astora', series: 'ds' },

    // Diablo Series
    { id: 'di_01', name: 'Loot Goblin', series: 'di' },

    // Mega Man Series
    { id: 'mm_01', name: 'Mega Man – Gold Edition', series: 'mm' },
    { id: 'mm_02', name: 'Mega Man', series: 'mm' },

    // Street Fighter Series
    { id: 'sf_01', name: 'Luke', series: 'sf' },
    { id: 'sf_02', name: 'Jamie', series: 'sf' },
    { id: 'sf_03', name: 'Kimberly', series: 'sf' }
];